/**
 * Type Definitions for Relearnable Learning Platform
 * 
 * These TypeScript interfaces define the core data models used throughout
 * the application for topics, lessons, quizzes, and user data.
 */

// ============================================================================
// COMPLEXITY & DIFFICULTY
// ============================================================================

/**
 * Difficulty levels for learning content.
 * Affects the depth, terminology, and assumed prior knowledge in generated content.
 */
export type Complexity = 'Beginner' | 'Intermediate' | 'Advanced';

// ============================================================================
// QUIZ TYPES
// ============================================================================

/**
 * Represents a single quiz question with multiple choice options.
 */
export interface QuizQuestion {
  /** The question text (may contain markdown/code blocks) */
  question: string;
  
  /** Array of 4 answer options */
  options: string[];
  
  /** Index of the correct answer (0-3) */
  correctAnswer: number;
  
  /** Explanation shown after answering, regardless of correctness */
  explanation: string;
  
  /** Optional: The specific concept this question tests */
  topic?: string;
}

/**
 * Tracks user progress through a quiz instance.
 */
export interface QuizProgress {
  /** Current question index (0-based) */
  currentQuestionIndex: number;
  
  /** Running score count */
  currentScore: number;
}

// ============================================================================
// FLASHCARD TYPES
// ============================================================================

/**
 * Individual flashcard content with highlighted keywords.
 */
export interface FlashcardData {
  /** Main content text for the flashcard */
  content: string;
  
  /** Key terms to highlight in the content */
  keywords: string[];
}

/**
 * A section within a lesson, containing flashcards and a quiz.
 */
export interface Section {
  /** Section title (e.g., "Introduction to Neural Networks") */
  title: string;
  
  /** Flashcards for this section (typically 3-5) */
  flashcards: FlashcardData[];
  
  /** Quiz questions for this section (typically 3) */
  quiz: QuizQuestion[];
}

// ============================================================================
// LESSON PLAN TYPES
// ============================================================================

/**
 * Complete lesson plan generated by AI.
 * Contains multiple sections, each with flashcards and quizzes.
 */
export interface LessonPlan {
  /** AI-corrected/formatted topic name */
  topicName?: string;
  
  /** Ordered sections of the lesson */
  sections: Section[];
  
  /** Comprehensive final exam (typically 10 questions) */
  finalQuiz: QuizQuestion[];
  
  /** Knowledge category (e.g., "Computer Science & Technology") */
  category: string;
  
  /** Placement quiz for Relearn mode (optional) */
  placementQuiz?: QuizQuestion[];
}

// ============================================================================
// KNOWLEDGE GRAPH TYPES
// ============================================================================

/**
 * Node in the knowledge/curriculum graph.
 * Represents a sub-topic or concept within a learning path.
 */
export interface KnowledgeNode {
  /** Unique identifier for the node */
  id: string;
  
  /** Display label for the node */
  label: string;
  
  /** Current status affecting visual appearance */
  status: 'locked' | 'unlocked' | 'completed' | 'current';
  
  /** Hierarchical level (0 = root, 1 = first children, etc.) */
  level: number;
}

/**
 * Edge connecting two nodes in the knowledge graph.
 */
export interface KnowledgeEdge {
  /** Source node ID */
  from: string;
  
  /** Target node ID */
  to: string;
}

/**
 * Complete knowledge graph structure for curriculum visualization.
 */
export interface KnowledgeGraph {
  /** All nodes in the graph */
  nodes: KnowledgeNode[];
  
  /** All edges connecting nodes */
  edges: KnowledgeEdge[];
}

// ============================================================================
// TOPIC TYPES
// ============================================================================

/**
 * Represents a learning topic/course that the user is studying.
 * Contains all state for progress tracking and lesson content.
 */
export interface Topic {
  /** Unique identifier */
  id: string;
  
  /** Topic name (e.g., "Machine Learning Fundamentals") */
  name: string;
  
  /** Difficulty level */
  complexity: Complexity;
  
  /** Overall completion status */
  status: 'in-progress' | 'completed';
  
  /** Learning mode */
  mode?: 'learn' | 'relearn';
  
  /** Current position in lesson */
  currentSectionIndex: number;
  currentCardIndex: number;
  
  /** Completed section indices */
  completedSectionIndices: number[];
  
  /** Scores for each section quiz */
  sectionScores: number[];
  
  /** Final exam score (when completed) */
  finalScore?: number;
  
  /** Timestamp of last access */
  lastAccessed: string;
  
  /** Completion timestamp */
  completedDate?: string;
  
  /** Generated lesson content */
  lessonPlan: LessonPlan;
  
  /** Current quiz state */
  quizProgress?: QuizProgress;
  
  /** UI state for loading indicator */
  isGenerating?: boolean;
  
  /** Curriculum tree for Relearn mode */
  knowledgeGraph?: KnowledgeGraph;
}

// ============================================================================
// USER TYPES
// ============================================================================

/**
 * User profile information and subscription status.
 */
export interface UserProfile {
  /** Supabase user ID */
  id: string;
  
  /** User email */
  email: string;
  
  /** Display name */
  full_name?: string;
  
  /** Profile picture URL */
  avatar_url?: string;
  
  /** Subscription status for access control */
  subscription_status: 'free' | 'active' | 'past_due' | 'canceled';
  
  /** Subscription plan type */
  plan_type: 'free' | 'monthly' | 'yearly';
  
  /** Last activity date for usage tracking */
  last_usage_date: string;
  
  /** Daily generation counters */
  learn_generations_count: number;
  relearn_generations_count: number;
  
  /** Theme preference */
  theme_preference?: 'light' | 'dark' | 'system';
}

/**
 * Aggregated user data including topics and mastery scores.
 */
export interface UserData {
  /** User ID */
  userId: string;
  
  /** User profile */
  profile?: UserProfile;
  
  /** All user's topics */
  topics: Topic[];
  
  /** Category mastery scores (category name -> score) */
  masteryScores: Record<string, number>;
  
  /** Topic recommendations */
  recommendations: Recommendation[];
}

// ============================================================================
// RECOMMENDATION TYPES
// ============================================================================

/**
 * AI-generated or pool-based topic recommendation.
 */
export interface Recommendation {
  /** Unique identifier */
  id: string;
  
  /** Suggested topic name */
  name: string;
  
  /** Suggested difficulty level */
  suggestedComplexity: Complexity;
  
  /** Explanation for why this topic is recommended */
  reason: string;
  
  /** Topic that triggered this recommendation */
  basedOnTopicId?: string;
  
  /** Whether this is an AI-suggested topic */
  is_suggested?: boolean;
  
  /** Suggested learning mode */
  suggestedMode?: 'learn' | 'relearn';
}
